layout_spectrum: 0.8234043
color:
  saturation: 1
  brandStrength: 0.0613257
  lightness: 0.8340425
  rhythmicContrast: 0
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
typography_spectrum: 0.8914894
name: 'doc:matiQ'
